version: '3.8'

services:
  mcoj-website:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
      - ./.env.local:/app/.env.local 